# Generated by Django 4.2.2 on 2023-06-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueconnection',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
